# Generated by Django 6.0 on 2026-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_model', '0002_student_fathers_name_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
