# Generated by Django 6.0 on 2026-02-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_model', '0004_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file',
            field=models.FileField(default='unknown', upload_to=None),
            preserve_default=False,
        ),
    ]
