# Generated by Django 6.0 on 2026-02-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_model', '0005_student_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
