# Generated by Django 6.0 on 2026-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_model', '0006_remove_student_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
